Create app skeleton
profydev/reddit-timer-KarthikRaju391 pull request #2
Opened 2021-07-13 11:21 UTC by KarthikRaju391

##Following changes have been implemented as per the acceptance criteria

- installed fonts 
- reset default browser styles with `styled-normalize`
- add global styles
- add router with routes `/` and `/search`

2021-07-13 11:24 UTC, mentor-tara commented
Great job :rocket: I'm a bit busy at the moment but I'll leave a review soon.

In the meantime **I'd suggest you start with the next task already. Even if you just check out a new branch** where you can continue to work on later. This is a great opportunity to learn professional Git workflows. 

[Head back to the course material to learn how to proceed.](https://profy.dev/project/reddit-timer/while-waiting)

PS: Of course we all know I'm not busy. I'm a bot :robot: But let's pretend that I am to have a more realistic team environment. We're here to practice after all, right? :smile:[](ckkp04mmw2vuk0b42idpakyah)

2021-07-13 13:29 UTC, mentor-tara requested changes
Before I approve this PR I'd like to share a few tips with you.

**Please go through the list below and review your own code first.** Imagine you're the reviewer or a person who didn't see the code before. Ask yourself if everything is clearly written and understandable. Are components and variables properly named?

Reviewing your own code with this mindset is an important practice that will help you learn a lot and write high-quality code.

To make it a bit easier for you here are the tips I promised. Some have a link :link: attached where you can find more information. I'd recommend reading the **bold tips** in any case. Feel free to check the boxes when you think your code fits.

**General:**
- [x] **Use yarn instead of npm** [:link:](https://profy.dev/project/reddit-timer/review-tips/use-yarn)
- [x] **Use a common project structure** [:link:](https://profy.dev/project/reddit-timer/review-tips/file-structure)

Once you're done with reviewing your own code feel free to check the [example implementation](https://profy.dev/project/reddit-timer/code-examples/create-app-skeleton-d137af0d-ce79-4289-ae9b-df6f0444a380). **But remember: It's an important exercise to review your code first on your own.**

When you think this PR is ready to be merged just let me know by requesting another review. I'll approve right away.[](ckkp0fo0g2w0w0b422db33fjd)

2021-07-14 07:47 UTC, mentor-tara approved these changes
Great work! :tada::tada::tada: You can merge the PR now.[](ckkqnj5io3o540b425ilxp80y)

2021-07-14 08:11 UTC, merged

2021-07-15 04:58 UTC, jkettmann commented on src/App.js
> +      </div> */}
The code looks very clean. I'd only remove this comment

2021-07-15 09:28 UTC, KarthikRaju391 commented
Just out of curiosity, is it really you responding or is it a bot 😬

On Thu, 15 Jul, 2021, 10:28 Johannes, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/App.js
> <https://github.com/profydev/reddit-timer-KarthikRaju391/pull/2#discussion_r670133269>
> :
>
> > +      {/* <div>
> +        App Placeholder
> +      </div> */}
>
> The code looks very clean. I'd only remove this comment
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/profydev/reddit-timer-KarthikRaju391/pull/2#pullrequestreview-706924229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQGEE7A5R5NNMVDF32ZM37TTXZTG7ANCNFSM5AI4AAPQ>
> .
>

2021-07-15 11:30 UTC, jkettmann commented
That was really me. My bots aren't that smart yet 🤓

2021-07-15 11:35 UTC, KarthikRaju391 commented
Haha, thanks!

On Thu, Jul 15, 2021 at 5:00 PM Johannes ***@***.***> wrote:

> That was really me. My bots aren't that smart yet 🤓
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/profydev/reddit-timer-KarthikRaju391/pull/2#issuecomment-880619514>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQGEE7BLHC72FRIDDLV25DTTX3BEXANCNFSM5AI4AAPQ>
> .
>